name: E2E

on:
  push:
  pull_request:

jobs:
  e2e:
    name: e2e (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e dg_core

      - name: Run end-to-end checks
        run: python e2e/run_e2e.py --artifacts-dir e2e_artifacts

      - name: Upload E2E artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-logs-${{ runner.os }}
          path: e2e_artifacts
          if-no-files-found: error
